name: Check
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  opentofu-plan-pull-request:
    name: OpenTofu Plan Pull Request
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      TFC_AWS_RUN_ROLE_ARN: ${{ secrets.amazon_role }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - uses: opentofu/setup-opentofu@000eeb8522f0572907c393e8151076c205fdba1b # v1.0.6

      - name: OpenTofu fmt
        id: fmt
        run: tofu fmt -check

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.amazon_role }}

      - name: OpenTofu Init
        id: init
        run: tofu init

      - name: OpenTofu Validate
        id: validate
        env:
          GITHUB_APP_ID: ${{ secrets.TF_GH_APP }}
          GITHUB_APP_INSTALLATION_ID: ${{ secrets.TF_GH_APP_INSTALL }}
          GITHUB_APP_PEM_FILE: ${{ secrets.TF_GH_APP_PEM }}
          DNSIMPLE_ACCOUNT: ${{ secrets.TF_DNSIMPLE_ACCOUNT }}
          DNSIMPLE_TOKEN: ${{ secrets.TF_DNSIMPLE_TOKEN }}
        run: tofu validate -no-color

      - name: OpenTofu Plan
        env:
          GITHUB_APP_ID: ${{ secrets.TF_GH_APP }}
          GITHUB_APP_INSTALLATION_ID: ${{ secrets.TF_GH_APP_INSTALL }}
          GITHUB_APP_PEM_FILE: ${{ secrets.TF_GH_APP_PEM }}
          DNSIMPLE_ACCOUNT: ${{ secrets.TF_DNSIMPLE_ACCOUNT }}
          DNSIMPLE_TOKEN: ${{ secrets.TF_DNSIMPLE_TOKEN }}
        run: |
          tofu plan -no-color -detailed-exitcode \
                    -var-file .tfvars \
                    -var='email_overrides=${{ secrets.email_overrides }}'

  opentofu-plan:
    name: OpenTofu Plan
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      TFC_AWS_RUN_ROLE_ARN: ${{ secrets.amazon_role }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - uses: opentofu/setup-opentofu@000eeb8522f0572907c393e8151076c205fdba1b # v1.0.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.amazon_role }}

      - name: OpenTofu Init
        id: init
        run: tofu init

      - name: OpenTofu Plan
        env:
          GITHUB_APP_ID: ${{ secrets.TF_GH_APP }}
          GITHUB_APP_INSTALLATION_ID: ${{ secrets.TF_GH_APP_INSTALL }}
          GITHUB_APP_PEM_FILE: ${{ secrets.TF_GH_APP_PEM }}
          DNSIMPLE_ACCOUNT: ${{ secrets.TF_DNSIMPLE_ACCOUNT }}
          DNSIMPLE_TOKEN: ${{ secrets.TF_DNSIMPLE_TOKEN }}
        run: |
          tofu plan -no-color -detailed-exitcode \
                    -var-file .tfvars \
                    -var='email_overrides=${{ secrets.email_overrides }}' \
                    -out=tfplan

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: tfplan
          path: tfplan


  opentofu-apply:
    name: OpenTofu Apply
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: 'production'
    needs: 'opentofu-plan'
    permissions:
      contents: read
      id-token: write
    env:
      TFC_AWS_RUN_ROLE_ARN: ${{ secrets.amazon_role }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - uses: opentofu/setup-opentofu@000eeb8522f0572907c393e8151076c205fdba1b # v1.0.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.amazon_role }}

      - name: OpenTofu Init
        id: init
        run: tofu init

      - name: Download Plan Artifact
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: tfplan

      - name: OpenTofu Apply
        env:
          GITHUB_APP_ID: ${{ secrets.TF_GH_APP }}
          GITHUB_APP_INSTALLATION_ID: ${{ secrets.TF_GH_APP_INSTALL }}
          GITHUB_APP_PEM_FILE: ${{ secrets.TF_GH_APP_PEM }}
          DNSIMPLE_ACCOUNT: ${{ secrets.TF_DNSIMPLE_ACCOUNT }}
          DNSIMPLE_TOKEN: ${{ secrets.TF_DNSIMPLE_TOKEN }}
        run: |
          tofu apply -no-color "tfplan"

  trivy:
    name: Trivy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
            persist-credentials: false

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4 # v0.32.0
        with:
          scan-type: config
          format: sarif
          output: trivy-results.sarif
          hide-progress: true
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: trivy-results.sarif
          path: trivy-results.sarif
